version: "3"
services:
  db:
    container_name: db
    build:
      context: .
      dockerfile: Database-PreRe.dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=ro
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=rathena_PRERE_db
      - MYSQL_USER=rathena_user_db
      - MYSQL_PASSWORD=changemeplease
      - MYSQL_TCP_PORT=3306
    ports:
      - "3306:3306"
    # TODO: Add volumes and require for image to startup

  log-db:
    container_name: log-db
    build:
      context: .
      dockerfile: Database-PreRe.dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=ro
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=rathena_PRERE_log
      - MYSQL_USER=rathena_user_log
      - MYSQL_PASSWORD=changemepleasetoo
      - MYSQL_TCP_PORT=3307
    ports:
      - "3307:3307"

  login-server:
    container_name: login-server
    build:
      context: .
      dockerfile: ServerBase.dockerfile
    environment:
      SERVER_NAME: login-server
    ports:
      - "6900:6900"
    restart: on-failure
    depends_on:
      - db

  map-server:
    container_name: map-server
    build:
      context: .
      dockerfile: ServerBase.dockerfile
    environment:
      SERVER_NAME: map-server
    ports:
      - "5121:5121"
    restart: on-failure
    depends_on:
      - db

  char-server:
    container_name: char-server
    build:
      context: .
      dockerfile: ServerBase.dockerfile
    environment:
      SERVER_NAME: char-server
    ports:
      - "6121:6121"
    restart: on-failure
    depends_on:
      - db
      - map-server