// Copyright (c) rAthena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),

BUILDIN_DEF(fakemage,""),
BUILDIN_DEF(fakeacolyte,""),
BUILDIN_DEF(fakeknight,""),
BUILDIN_DEF(fakepriest,""),
BUILDIN_DEF(fakewizard,""),
BUILDIN_DEF(fakehunter,""),
BUILDIN_DEF(fakenpc,""),
BUILDIN_DEF(fakerogue,""),
BUILDIN_DEF(fakealchemist,""),
BUILDIN_DEF(fakecrusader,""),
BUILDIN_DEF(fakemonk,""),
BUILDIN_DEF(fakesage,""),
BUILDIN_DEF(fakegunslinger,""),
BUILDIN_DEF(fakeninja,""),
BUILDIN_DEF(fakeruneknight,""),
BUILDIN_DEF(fakewarlock,""),
BUILDIN_DEF(fakearchbishop,""),
BUILDIN_DEF(fakeranger,""),
BUILDIN_DEF(fakeshadowchaser,""),
BUILDIN_DEF(fakeroyalguard,""),
BUILDIN_DEF(fakesura,""),
BUILDIN_DEF(fakesorcerer,""),
BUILDIN_DEF(fakekageobo,""),