# This is the mostly original file from rathena.
version: "3.7"

services:
    db:
        image: "mariadb:bionic"
        container_name: "rathena_db"
        ports:
            - "3306:3306" # allow DB connections from host
        volumes:
            - "rathenadb:/var/lib/mysql" # save database to local disk
            - "../../sql-files/:/docker-entrypoint-initdb.d" # initialize db with ./sql-files
        environment:
            MYSQL_ROOT_PASSWORD: ragnarok
            MYSQL_DATABASE: ragnarok
            MYSQL_USER: ragnarok
            MYSQL_PASSWORD: ragnarok

    builder:
        image: "rathena:local"
        container_name: "rathena-builder"
        command: "/rathena/tools/docker/builder.sh"
        volumes:
            - "../..:/rathena" # mount git repo directory inside container
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            # BUILDER_CONFIGURE: "--enable-packetver=20211103"
            BUILDER_CONFIGURE: "--enable-packetver=20201228"
    login:
        image: "rathena:local"
        container_name: "rathena-login"
        command: sh -c "/bin/wait-for db:3306 -- /rathena/login-server"
        ports:
            - "6900:6900" # login server
        volumes:
            - "../..:/rathena" # mount git repo directory inside container
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
    char:
        image: "rathena:local"
        container_name: "rathena-char"
        command: sh -c "/bin/wait-for db:3306 -- /rathena/char-server"
        ports:
            - "6121:6121" # char server
        volumes:
            - "../..:/rathena" # mount git repo directory inside container
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - login
    map:
        image: "rathena:local"
        container_name: "rathena-map"
        command: sh -c "/bin/wait-for db:3306 -- /rathena/map-server"
        ports:
            - "5121:5121" # map server
        volumes:
            - "../..:/rathena" # mount git repo directory inside container
        init: true # helps with signal forwarding and process reaping
        tty: true
        stdin_open: true
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - char
    registration:
        image: "registration"
        container_name: "registration"
        ports:
            - "9001:443"
        build:
            context: ./char-registration
            dockerfile: Dockerfile
        volumes:
            # Read-only access to SSL certs one folder outside of repo root
            - "../../../cert.pem:/usr/server/cert.pem:ro"
            - "../../../privkey.pem:/usr/server/privkey.pem:ro"
        environment:
            EXPRESS_PORT: 443
            EXPRESS_CERT_PATH: cert.pem
            EXPRESS_CERT_PRIV_KEY_PATH: privkey.pem
            DB_HOST: db
            DB_USER: ragnarok
            DB_PASSWORD: ragnarok
            DB_DATABASE_NAME: ragnarok
            DB_ENABLE_DEBUG: false

volumes:
    rathenadb:
